name: 'snowflake_tpch_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake_tpch_demo'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  snowflake_tpch_demo:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: table
      +schema: staging  # This will create tables in your_database.staging
    marts:
      +materialized: table
      +schema: marts    # This will create tables in your_database.marts
