name: 'snowflake_tpch_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake_tpch_demo'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

# Configuring models
models:
  snowflake_tpch_demo:
    staging:
      +materialized: table
      +schema: staging  
    marts:
      +materialized: table
      +schema: marts  
