snowflake_tpch_demo:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: 'ACCOUNTADMIN'
      warehouse: 'DEV_WH'
      database: 'DEMO_DB'
      schema: 'TPCH_SF1'
      account: ' '
      user: ' '
